apiVersion: projectcontour.io/v1
kind: TLSCertificateDelegation
metadata:
  name: tsladmin-del
  namespace: tlsadmin
spec:
  delegations:
    - secretName: admin-tls-secret
      targetNamespaces:
      - "*"